stages:
  - lint
  - build
  - test

variables:
  RUSTFLAGS: "-Dwarnings"
  SQLX_OFFLINE: true

.backend_jobs: &backend_job
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
    - cp .env.example .env
  cache:
    paths:
      - target/

.web_jobs: &web_job
  image: node:20.11.0
  before_script:
    - cp .env.example .env
    - cd ./web
    - npm ci
  cache:
    key:
      files:
        - package-lock.json

backend_lint:
  <<: *backend_job
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy

backend_build:
  <<: *backend_job
  stage: build
  script:
    - cp .env.example .env
    - cargo build --verbose

backend_test:
  <<: *backend_job
  stage: test
  script:
    - cargo test --verbose

web-lint:
  <<: *web_job
  stage: lint
  script:
    - npm run lint

web-build:
  <<: *web_job
  stage: build
  script:
    - npm run build

web-test-unit:
  <<: *web_job
  stage: test
  script:
    - npm run test:unit

web-test-e2e:
  image: cypress/browsers:node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1
  stage: test
  script:
    - cd ./web
    - npm ci
    - npm run preview &
    - npx cypress run --browser chrome
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 3 day
