services:
  postgres:
    image: postgres:16.2
    container_name: moner_postgres
    ports:
      - 5432:5432
    env_file:
      - ../apps/server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
